import { NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { authenticateRequest } from "@/lib/api-auth";
import { db } from "@videohost/db";
import { getPublicCdnUrl } from "@/lib/s3";
import {
  buildAutoGeneratedLabel,
  getSubtitlePlaybackUrl,
  getSubtitleS3Key,
  normalizeSubtitleLabel,
  normalizeSubtitleLanguage,
} from "@/lib/subtitles";
import {
  TRANSCRIPTION_ALREADY_RUNNING_CODE,
  addTranscriptionJob,
  getWhisperConfig,
  hasPendingTranscriptionJob,
} from "@/lib/queue";

const MAX_SUBTITLES_PER_VIDEO = 20;

function isAudioRendition(resolution?: string | null): boolean {
  return (resolution || "").toLowerCase().includes("audio");
}

/**
 * POST /api/v1/videos/:id/subtitles/transcribe
 *
 * Starts an automatic subtitle generation job for a video:
 * - Requires a dedicated audio rendition (else 400).
 * - Dispatches a transcription job to the worker (container HTTP + BullMQ),
 *   passing the CDN link of the audio rendition's .m3u8 plus every other
 *   param the worker needs (Whisper URL/key, S3 creds, storage key, callback).
 * - The worker uploads the VTT and reports back to /transcription-callback,
 *   which creates the subtitle track.
 */
export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const authCtx = await authenticateRequest(req);
  if (!authCtx) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const video = await db.video.findFirst({
    where: { id, organizationId: authCtx.orgId },
    include: { renditions: true },
  });
  if (!video) return NextResponse.json({ error: "Video not found" }, { status: 404 });

  const audioRendition = video.renditions.find((r) => isAudioRendition(r.resolution));
  if (!audioRendition) {
    return NextResponse.json(
      { error: "This video does not have a dedicated audio rendition to generate subtitles from." },
      { status: 400 }
    );
  }

  let language = "en";
  let label: string | null = null;
  try {
    const body = await req.json().catch(() => ({} as any));
    if (typeof body?.language === "string" && body.language.trim()) language = body.language;
    if (typeof body?.label === "string" && body.label.trim()) label = body.label;
  } catch {
    // No JSON body — fall back to defaults.
  }

  const normalizedLanguage = normalizeSubtitleLanguage(language);
  // Auto-generated tracks always carry the language code in the name
  // (e.g. "Auto-generated (en)"); an explicit label is respected as-is.
  const normalizedLabel = label
    ? normalizeSubtitleLabel(label, normalizedLanguage)
    : buildAutoGeneratedLabel(normalizedLanguage);

  const existingCount = await db.videoSubtitle.count({ where: { videoId: id } });
  if (existingCount >= MAX_SUBTITLES_PER_VIDEO) {
    return NextResponse.json(
      { error: `Subtitle limit reached (max ${MAX_SUBTITLES_PER_VIDEO} per video). Delete one to add another.` },
      { status: 400 }
    );
  }

  const duplicate = await db.videoSubtitle.findUnique({
    where: { videoId_language_label: { videoId: id, language: normalizedLanguage, label: normalizedLabel } },
  });
  if (duplicate) {
    const displayName = normalizedLabel.endsWith(`(${normalizedLanguage})`)
      ? normalizedLabel
      : `${normalizedLabel} (${normalizedLanguage})`;
    return NextResponse.json(
      {
        error: `A subtitle track "${displayName}" already exists.`,
        src: await getSubtitlePlaybackUrl(duplicate.storageKey),
      },
      { status: 409 }
    );
  }

  const whisper = getWhisperConfig();
  if (!whisper.url || !whisper.apiKey) {
    return NextResponse.json(
      { error: "Transcription service is not configured (WHISPER_API_URL / WHISPER_API_KEY)." },
      { status: 500 }
    );
  }

  if (await hasPendingTranscriptionJob(id)) {
    return NextResponse.json(
      { error: "A transcription job is already running for this video.", pending: true },
      { status: 409 }
    );
  }

  // The audio rendition is the last representation in the DASH ladder
  // (worker appends "Audio (AAC)" after the video renditions), so its HLS
  // media playlist index equals the number of video renditions.
  const audioIndex = video.renditions.filter((r) => !isAudioRendition(r.resolution)).length;
  const dashBaseKey = audioRendition.storageKey.replace(/\/(?:master\.(?:mpd|m3u8)|manifest\.mpd)?$/, "");
  const audioHlsUrl = getPublicCdnUrl(`${dashBaseKey}/media_${audioIndex}.m3u8`);
  const fallbackHlsUrl = getPublicCdnUrl(`${dashBaseKey}/master.m3u8`);

  const subtitleId = randomUUID();
  const storageKey = getSubtitleS3Key(video.organizationId, id, subtitleId, normalizedLanguage);

  try {
    await addTranscriptionJob({
      videoId: id,
      orgId: video.organizationId,
      audioHlsUrl,
      fallbackHlsUrl,
      language: normalizedLanguage,
      label: normalizedLabel,
      subtitleId,
      storageKey,
    });
  } catch (e: any) {
    console.error("[Subtitles Transcribe Dispatch Error]", e);
    if ((e as any)?.code === TRANSCRIPTION_ALREADY_RUNNING_CODE) {
      return NextResponse.json(
        { error: "A transcription job is already running for this video.", pending: true },
        { status: 409 }
      );
    }
    return NextResponse.json(
      { error: e?.message || "Failed to start transcription job." },
      { status: 500 }
    );
  }

  return NextResponse.json(
    {
      success: true,
      message: "Transcription started. The auto-generated subtitle will appear here when ready.",
      subtitleId,
      storageKey,
      language: normalizedLanguage,
      label: normalizedLabel,
    },
    { status: 202 }
  );
}

/**
 * GET /api/v1/videos/:id/subtitles/transcribe
 *
 * Transcription status for the video details UI: `{ pending: boolean }`.
 * True while an auto-generated transcription is queued/running, so the UI
 * can keep the Auto-generate trigger disabled (also across page reloads).
 */
export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const authCtx = await authenticateRequest(req);
  if (!authCtx) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const video = await db.video.findFirst({
    where: { id, organizationId: authCtx.orgId },
    select: { id: true },
  });
  if (!video) return NextResponse.json({ error: "Video not found" }, { status: 404 });

  const pending = await hasPendingTranscriptionJob(id);
  return NextResponse.json({ pending });
}
