import { NextResponse } from "next/server";
import { db } from "@videohost/db";
import { deleteFileFromS3 } from "@/lib/s3";
import { buildAutoGeneratedLabel, getSubtitlePlaybackUrl } from "@/lib/subtitles";
import { clearTranscriptionInFlight, markTranscriptionStarted } from "@/lib/queue";

const MAX_SUBTITLES_PER_VIDEO = 20;

/**
 * Worker callback for Whisper transcription jobs.
 *
 * - PROCESSING: progress heartbeat, acknowledged without touching the video
 *   row (transcription must never clobber transcode status/progress).
 * - READY: the worker uploaded the VTT to `storageKey` — create the
 *   VideoSubtitle track pointing at it.
 * - FAILED/CANCELLED: nothing to persist, just acknowledge.
 */
export async function POST(req: Request) {
  try {
    const workerSecret = process.env.WORKER_SECRET_TOKEN;
    if (workerSecret) {
      const authHeader = req.headers.get("authorization");
      const secretHeader = req.headers.get("x-worker-secret");
      const token = authHeader?.startsWith("Bearer ") ? authHeader.substring(7) : secretHeader;

      if (token !== workerSecret) {
        return NextResponse.json({ error: "Unauthorized callback request" }, { status: 401 });
      }
    }

    const payload = await req.json();
    console.log(`[Transcription Callback] Received callback payload:`, JSON.stringify(payload, null, 2));
    const {
      videoId,
      organizationId,
      subtitleId,
      storageKey,
      language,
      label,
      status,
      error,
      sizeBytes,
    } = payload;

    if (!videoId) {
      return NextResponse.json({ error: "videoId is required" }, { status: 400 });
    }

    if (status === "PROCESSING") {
      // Heartbeat — keep the in-flight marker alive so duplicate triggers
      // stay blocked while the worker is still working.
      markTranscriptionStarted(videoId);
      return NextResponse.json({ success: true, status: "PROCESSING", videoId });
    }

    // Terminal states (READY / FAILED / CANCELLED): the job is done, so the
    // UI may trigger a new transcription again.
    clearTranscriptionInFlight(videoId);

    if (status !== "READY") {
      console.log(`[Transcription Callback] Video ${videoId} transcription ${status || "FAILED"}: ${error || "Unknown error"}`);
      return NextResponse.json({ success: true, status: status || "FAILED", videoId });
    }

    const video = await db.video.findUnique({ where: { id: videoId } });
    if (!video) {
      return NextResponse.json({ error: "Video not found" }, { status: 404 });
    }

    if (organizationId && organizationId !== video.organizationId) {
      return NextResponse.json({ error: "Organization mismatch" }, { status: 403 });
    }
    if (!subtitleId || !storageKey) {
      return NextResponse.json({ error: "subtitleId and storageKey are required" }, { status: 400 });
    }

    const expectedPrefix = `videos/${video.organizationId}/${videoId}/subtitles/`;
    if (!storageKey.startsWith(expectedPrefix) || !storageKey.toLowerCase().endsWith(".vtt")) {
      return NextResponse.json({ error: "Invalid subtitle storageKey." }, { status: 400 });
    }

    const normalizedLanguage = String(language || "en").trim().toLowerCase().replace(/[^a-z0-9-]/g, "").slice(0, 12) || "en";
    const rawLabel = String(label || "").trim();
    // Auto-generated tracks carry the language code in the name; upgrade the
    // legacy plain "Auto-generated" label from in-flight jobs on rollout.
    const normalizedLabel =
      !rawLabel || rawLabel === "Auto-generated"
        ? buildAutoGeneratedLabel(normalizedLanguage)
        : rawLabel.slice(0, 80);

    const existingCount = await db.videoSubtitle.count({ where: { videoId } });
    if (existingCount >= MAX_SUBTITLES_PER_VIDEO) {
      deleteFileFromS3(storageKey).catch((e) =>
        console.error("[Transcription Callback] Failed to delete orphaned VTT from S3:", e)
      );
      return NextResponse.json({ error: "Subtitle limit reached for this video." }, { status: 400 });
    }

    // Idempotency: worker retries must not create duplicate tracks.
    const existing = await db.videoSubtitle.findUnique({ where: { id: subtitleId } }).catch(() => null);
    if (existing) {
      return NextResponse.json({
        success: true,
        status: "READY",
        videoId,
        subtitle: {
          id: existing.id,
          label: existing.label,
          language: existing.language,
          isDefault: existing.isDefault,
          src: await getSubtitlePlaybackUrl(existing.storageKey),
        },
      });
    }

    const duplicate = await db.videoSubtitle.findUnique({
      where: { videoId_language_label: { videoId, language: normalizedLanguage, label: normalizedLabel } },
    });
    if (duplicate) {
      deleteFileFromS3(storageKey).catch((e) =>
        console.error("[Transcription Callback] Failed to delete duplicate VTT from S3:", e)
      );
      const displayName = normalizedLabel.endsWith(`(${normalizedLanguage})`)
        ? normalizedLabel
        : `${normalizedLabel} (${normalizedLanguage})`;
      return NextResponse.json(
        { error: `A subtitle track "${displayName}" already exists.` },
        { status: 409 }
      );
    }

    const created = await db.videoSubtitle.create({
      data: {
        id: subtitleId,
        videoId,
        label: normalizedLabel,
        language: normalizedLanguage,
        storageKey,
        sizeBytes: Number(sizeBytes) || 0,
        // First-ever track becomes default automatically (same as manual uploads).
        isDefault: existingCount === 0,
      },
    });

    if (created.isDefault) {
      await db.videoSubtitle.updateMany({
        where: { videoId, id: { not: created.id } },
        data: { isDefault: false },
      });
    }

    console.log(`[Transcription Callback] Video ${videoId} auto subtitle ready: ${created.id} (${normalizedLanguage})`);

    return NextResponse.json(
      {
        success: true,
        status: "READY",
        videoId,
        subtitle: {
          id: created.id,
          label: created.label,
          language: created.language,
          isDefault: created.isDefault,
          sizeBytes: created.sizeBytes,
          createdAt: created.createdAt,
          src: await getSubtitlePlaybackUrl(created.storageKey),
        },
      },
      { status: 201 }
    );
  } catch (err: any) {
    console.error("[Transcription Callback Error]", err);
    return NextResponse.json({ error: err?.message || "Internal server error" }, { status: 500 });
  }
}
